{
 "title": "Default",
 "time": { "from": "2025-11-23T18:58:23.698Z", "to": "2025-11-23T19:17:48.297Z" },
 "panels": [
  {
   "title": "Request count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "flask_request_latency_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "flask_request_latency_seconds_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Audio analyze time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "audio_analysis_duration_seconds_sum",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}